---
# defaults file for wordpress

# MariaDB Settings
mariadb_root_password: "supersecretrootpassword" 
wordpress_db_name: "wordpress_db"
wordpress_db_user: "wordpress_user"
wordpress_db_password: "supersecretdbpassword"
mariadb_packages:
  - mariadb-server
  - mariadb-client
  - python3-pymysql

# Apache Settings
apache_packages:
  - apache2 # For Debian/Ubuntu
  # - httpd  # For RHEL/CentOS

apache_vhost_dir: "/etc/apache2/sites-available" # For Debian/Ubuntu
# apache_vhost_dir: "/etc/httpd/conf.d"          # For RHEL/CentOS

wordpress_web_root: "/var/www/wordpress"
wordpress_domain: "localhost"

# WordPress Settings
wordpress_version: "latest" # یا یک نسخه خاص مثل "6.2.2"
wordpress_download_url: >-
  {% if wordpress_version == "latest" %}
  https://wordpress.org/latest.tar.gz
  {% else %}
  https://wordpress.org/wordpress-{{ wordpress_version }}.tar.gz
  {% endif %}
wordpress_local_path: "/tmp/wordpress.tar.gz"
wordpress_install_dir: "{{ wordpress_web_root }}"
wordpress_config_file: "{{ wordpress_install_dir }}/wp-config.php"
wordpress_owner: "www-data" # User for web server (www-data for Debian/Ubuntu, apache for RHEL/CentOS)
wordpress_group: "www-data" # Group for web server (www-data for Debian/Ubuntu, apache for RHEL/CentOS)