---
- name: Deploy WordPress Stack
  hosts: webservers
  become: yes
  vars:
    wordpress_domain: "node4.mylab.local"
    
    # For changing "mariadb_root_password" and "wordpress_db_password" refer to roles/wordpress/vars/vault.yml "123456Aa@" ;)
    
    # اگر نیاز به تغییر نام دیتابیس یا یوزر وردپرس دارید، می‌توانید اینجا اضافه کنید:
    # wordpress_db_name: "my_custom_wp_db"
    # wordpress_db_user: "my_custom_wp_user"

    # مثال برای تنظیم نسخه وردپرس:
    # wordpress_version: "6.2.2"
    # wordpress_download_url: "https://wordpress.org/wordpress-6.2.2.tar.gz"

  roles:
    - role: wordpress
