---
# tasks file for wordpress

- name: Include sensitive encrypted variables from vars/vault.yml
  ansible.builtin.include_vars: vault.yml

- name: Include MariaDB setup tasks
  ansible.builtin.include_tasks: mariadb.yml

- name: Include Apache setup tasks
  ansible.builtin.include_tasks: apache.yml

- name: Include WordPress installation and configuration tasks
  ansible.builtin.include_tasks: wordpress.yml