---
- name: Install MariaDB packages
  ansible.builtin.package:
    name: "{{ mariadb_packages }}"
    state: present

- name: Ensure MariaDB service is running and enabled
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: yes

- name: Ensure MariaDB root password is set
  community.mysql.mysql_user:
    name: root
    host: localhost
    password: "{{ mariadb_root_password }}"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    check_implicit_admin: true
    column_case_sensitive: false
    state: present

- name: Create WordPress database
  community.mysql.mysql_db:
    name: "{{ wordpress_db_name }}"
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"

- name: Create WordPress database user
  community.mysql.mysql_user:
    name: "{{ wordpress_db_user }}"
    password: "{{ wordpress_db_password }}"
    priv: "{{ wordpress_db_name }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"

