$ANSIBLE_VAULT;1.1;AES256
38643037326261373766343630363139633263646264633831323431386438343338326531666636
6436383035363137373032383539346165393236316531640a666234646131396466636264663864
63653036323436353161393230633265326432303936303730343130356665363430666437386139
6632353232316361630a643433326134343862353536643637326366653263636432343861343734
61343233613038373138326465306535383139386666643639306239613764303365633961323739
33663232383133373937336162393062653562633034346364373531353463666563376137316535
64636633376163656534366332323961636636363461333532396337313063666162353130313365
63336463376437366137666238663934633331383561616634613862313032663737343937383939
61333733613461636661303534383031316531663639333363336535646562633738393139656137
35376233393961333365313833393536326165303030336631326661613137653239646232663765
30303862316137376266323865313661393932623465633436373939383831626562376636336431
32636135386333653730313666313231653564643934383763393761666134363561393762623131
33343633323963666262623731323332366435346165346166363261356163353930613836653831
64303433613962633233626634323433323838393538326565336463356263346539363637363638
30366439373865333733366236383962613531323133353962313562376363336361643732323739
30616263646631633635383639306237306133656138613966306436613734326564323739333739
32333736663634656563623732653934646236623635386261366233643765393638383830656664
62376165363261656236323964323531656661373738323764383138616364323330323635316339
63636337326561313133613533316234366132356430373532333330383862303336346534623831
61636132383338326630353838626237623330396464303262613233373462653066636438363839
66323433333935373630623638336230383239356262393831633162653833376639346666353563
30393961653066343730623038323161346464623036343137613935303161326339616433326537
34643539646662666462353936343465313839326662313837303832303665616631323864353230
39616234386264323534373262623137663331623230623830383964313938643135643066336665
62333732616438353937386132666361653564386138636432366465333461376565393462373733
63633965376336633463313932633133306266306566623666356365393462303361653962363133
34353332316162396238366432326138623631333863343138616465353034626435363331356263
38366464666430636634373164333764306430313039636537393939383834656261336666663166
32663763383530666331643465333365353165376632663534336139663363306631316363643630
35613437356366366331633138393433303032306562363364633838323835646332653361316463
37636637646633616237616266336663363438303939643732623439326630653062386137643463
31313130386334363339623539643231613164663537346237386639383838616435303233373164
62306632353839306331666431303034383465336162336666366239653761303132303037383039
34353039306235663331383439626534666333313661653935613365653466326564623966643539
37383038663661656434666661666336623637323665623130363137316131356434373139643139
38323039316362373131373431333937333139653663643835356432616134306334323863386437
65396263613234376665616666653263316138356630303061643931313561303731336163396434
64353033343835623236396238613061623635326635376265383539343430613563343964316339
35656238666236613566666638393232356362353630646634616663336365363462326439343231
38373136366466626232323164393532373365656239303961383932636463626239636562653466
36633534366236336166356535373739353237643933303665383166613238323165376637363539
65303562333533383038323237303163646235326665623939313462353264303232363239613865
39323963386533336137306639376533636233653163363633393461383336313561303566396639
31386466346537393733343832633931393832313562323536326438343863323661643265313436
33356239326333306534313365363162353262643261393439313363313139386531
